[workspace]
members = [
    "bongo_cat",
]
resolver = "2"

[profile.release]
debug = true

[workspace.dependencies]
serde_json = "1.0"
log = "0.4"
once_cell = "1.21"
anyhow = "1.0"
ipc-channel = "0.19"
parking_lot = "0.12"
rdev = { git = "https://github.com/ayangweb/rdev" }
