[package]
name = "bongo_cat"
version = "0.1.0"
edition = "2024"

[dependencies]
ipc-channel = { workspace = true }
rdev = { workspace = true }
serde_json = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }